# data.py — Panini FIFA World Cup 2026 (980 stickers, 48 teams)
# Fuente: Diamond Cards / Panini official checklist — datos 100% verificados

def _team(code, name, flag, color, players):
    """
    players: 18 (name, pos) tuples → slots 2-12 y 14-20.
    Construye los 20 stickers: logo(1) + 11 jugadores(2-12) + foto(13) + 7 jugadores(14-20).
    """
    s = [{"id": f"{code}1",  "team": code, "name": "Escudo del Equipo",
          "pos": "LOG", "foil": True, "photo": False}]
    for i, (n, p) in enumerate(players[:11], 2):
        s.append({"id": f"{code}{i}",  "team": code, "name": n, "pos": p, "foil": False, "photo": False})
    s.append({"id": f"{code}13", "team": code, "name": "Foto del Equipo",
              "pos": "FOT", "foil": False, "photo": True})
    for i, (n, p) in enumerate(players[11:18], 14):
        s.append({"id": f"{code}{i}",  "team": code, "name": n, "pos": p, "foil": False, "photo": False})
    return {"code": code, "name": name, "flag": flag, "color": color, "stickers": s}


TEAMS = [
    # ── ARG ─────────────────────────────────────────────────────────────────
    _team("ARG", "Argentina", "ar", "#75AADB", [
        ("Emiliano Martínez",     "POR"), ("Nahuel Molina",         "DEF"),
        ("Cristian Romero",       "DEF"), ("Nicolás Otamendi",      "DEF"),
        ("Nicolás Tagliafico",    "DEF"), ("Leonardo Balerdi",      "DEF"),
        ("Enzo Fernández",        "MED"), ("Alexis Mac Allister",   "MED"),
        ("Rodrigo De Paul",       "MED"), ("Exequiel Palacios",     "MED"),
        ("Leandro Paredes",       "MED"),
        ("Nico Paz",              "MED"), ("Franco Mastantuono",    "MED"),
        ("Nico González",         "DEL"), ("Lionel Messi",          "DEL"),
        ("Lautaro Martínez",      "DEL"), ("Julián Álvarez",        "DEL"),
        ("Giuliano Simeone",      "DEL"),
    ]),
    # ── AUT ─────────────────────────────────────────────────────────────────
    _team("AUT", "Austria", "at", "#ED2939", [
        ("Alexander Schlager",    "POR"), ("Patrick Pentz",         "POR"),
        ("David Alaba",           "DEF"), ("Kevin Danso",           "DEF"),
        ("Philipp Lienhart",      "DEF"), ("Stefan Posch",          "DEF"),
        ("Philipp Mwene",         "DEF"), ("Alexander Prass",       "MED"),
        ("Xaver Schlager",        "MED"), ("Marcel Sabitzer",       "MED"),
        ("Konrad Laimer",         "MED"),
        ("Florian Grillitsch",    "MED"), ("Nicolas Seiwald",       "MED"),
        ("Romano Schmid",         "MED"), ("Patrick Wimmer",        "DEL"),
        ("Christoph Baumgartner", "MED"), ("Michael Gregoritsch",   "DEL"),
        ("Marko Arnautović",      "DEL"),
    ]),
    # ── AUS ─────────────────────────────────────────────────────────────────
    _team("AUS", "Australia", "au", "#00843D", [
        ("Mathew Ryan",           "POR"), ("Joe Gauci",             "POR"),
        ("Harry Souttar",         "DEF"), ("Alessandro Circati",    "DEF"),
        ("Jordan Bos",            "DEF"), ("Aziz Behich",           "DEF"),
        ("Cameron Burgess",       "DEF"), ("Lewis Miller",          "DEF"),
        ("Milos Degenek",         "DEF"), ("Jackson Irvine",        "MED"),
        ("Riley McGree",          "MED"),
        ("Aiden O'Neill",         "MED"), ("Connor Metcalfe",       "MED"),
        ("Patrick Yazbek",        "MED"), ("Craig Goodwin",         "MED"),
        ("Kusini Yengi",          "DEL"), ("Nestory Irankunda",     "DEL"),
        ("Mohamed Toure",         "DEL"),
    ]),
    # ── BEL ─────────────────────────────────────────────────────────────────
    _team("BEL", "Bélgica", "be", "#EF3340", [
        ("Thibaut Courtois",      "POR"), ("Arthur Theate",         "DEF"),
        ("Timothy Castagne",      "DEF"), ("Zeno Debast",           "DEF"),
        ("Brandon Mechele",       "DEF"), ("Maxim De Cuyper",       "DEF"),
        ("Thomas Meunier",        "DEF"), ("Youri Tielemans",       "MED"),
        ("Amadou Onana",          "MED"), ("Nicolas Raskin",        "MED"),
        ("Alexis Saelemaekers",   "MED"),
        ("Hans Vanaken",          "MED"), ("Kevin De Bruyne",       "MED"),
        ("Jérémy Doku",           "DEL"), ("Charles De Ketelaere",  "MED"),
        ("Leandro Trossard",      "DEL"), ("Loïs Openda",           "DEL"),
        ("Romelu Lukaku",         "DEL"),
    ]),
    # ── BIH ─────────────────────────────────────────────────────────────────
    _team("BIH", "Bosnia y Herzegovina", "ba", "#002395", [
        ("Nikola Vasilj",         "POR"), ("Amer Dedic",            "DEF"),
        ("Sead Kolasinac",        "DEF"), ("Tarik Muharemovic",     "DEF"),
        ("Nihad Mujakic",         "DEF"), ("Nikola Katic",          "DEF"),
        ("Amir Hadziahmetovic",   "MED"), ("Benjamin Tahirovic",    "MED"),
        ("Armin Gigovic",         "MED"), ("Ivan Sunjic",           "MED"),
        ("Ivan Basic",            "MED"),
        ("Dzenis Burnic",         "MED"), ("Esmir Bajraktarevic",   "MED"),
        ("Amar Memic",            "DEF"), ("Ermedin Demirovic",     "DEL"),
        ("Edin Dzeko",            "DEL"), ("Samed Bazdar",          "DEL"),
        ("Haris Tabakovic",       "DEL"),
    ]),
    # ── BRA ─────────────────────────────────────────────────────────────────
    _team("BRA", "Brasil", "br", "#009C3B", [
        ("Alisson",               "POR"), ("Bento",                 "POR"),
        ("Marquinhos",            "DEF"), ("Éder Militão",          "DEF"),
        ("Gabriel Magalhães",     "DEF"), ("Danilo",                "DEF"),
        ("Wesley",                "DEF"), ("Lucas Paquetá",         "MED"),
        ("Casemiro",              "MED"), ("Bruno Guimarães",       "MED"),
        ("Luiz Henrique",         "MED"),
        ("Vinicius Júnior",       "DEL"), ("Rodrygo",               "DEL"),
        ("João Pedro",            "DEL"), ("Matheus Cunha",         "DEL"),
        ("Gabriel Martinelli",    "DEL"), ("Raphinha",              "DEL"),
        ("Estévão",               "DEL"),
    ]),
    # ── CAN ─────────────────────────────────────────────────────────────────
    _team("CAN", "Canadá", "ca", "#FF0000", [
        ("Dayne St. Clair",       "POR"), ("Alphonso Davies",       "DEF"),
        ("Alistair Johnston",     "DEF"), ("Samuel Adekugbe",       "DEF"),
        ("Richie Laryea",         "DEF"), ("Derek Cornelius",       "DEF"),
        ("Moïse Bombito",         "DEF"), ("Kamal Miller",          "DEF"),
        ("Stephen Eustáquio",     "MED"), ("Ismaël Koné",           "MED"),
        ("Jonathan Osorio",       "MED"),
        ("Jacob Shaffelburg",     "MED"), ("Mathieu Choinière",     "MED"),
        ("Niko Sigur",            "MED"), ("Tajon Buchanan",        "DEL"),
        ("Liam Millar",           "DEL"), ("Cyle Larin",            "DEL"),
        ("Jonathan David",        "DEL"),
    ]),
    # ── CPV ─────────────────────────────────────────────────────────────────
    _team("CPV", "Cabo Verde", "cv", "#003893", [
        ("Vozinha",               "POR"), ("Logan Costa",           "DEF"),
        ("Pico",                  "DEF"), ("Diney",                 "DEF"),
        ("Steven Moreira",        "DEF"), ("Wagner Pina",           "MED"),
        ("Joao Paulo",            "MED"), ("Yannick Semedo",        "MED"),
        ("Kevin Pina",            "MED"), ("Patrick Andrade",       "MED"),
        ("Jamiro Monteiro",       "MED"),
        ("Deroy Duarte",          "MED"), ("Garry Rodrigues",       "DEL"),
        ("Jovane Cabral",         "DEL"), ("Ryan Mendes",           "DEL"),
        ("Dailon Livramento",     "DEL"), ("Willy Semedo",          "DEL"),
        ("Bebe",                  "DEL"),
    ]),
    # ── COL ─────────────────────────────────────────────────────────────────
    _team("COL", "Colombia", "co", "#FCD116", [
        ("Camilo Vargas",         "POR"), ("David Ospina",          "POR"),
        ("Dávinson Sánchez",      "DEF"), ("Yerry Mina",            "DEF"),
        ("Daniel Muñoz",          "DEF"), ("Johan Mojica",          "DEF"),
        ("Jhon Lucumí",           "DEF"), ("Santiago Arias",        "DEF"),
        ("Jefferson Lerma",       "MED"), ("Kevin Castaño",         "MED"),
        ("Richard Ríos",          "MED"),
        ("James Rodríguez",       "MED"), ("Juan F. Quintero",      "MED"),
        ("Jorge Carrascal",       "MED"), ("Jon Arias",             "DEL"),
        ("Jhon Córdoba",          "DEL"), ("Luis Suárez",           "DEL"),
        ("Luis Díaz",             "DEL"),
    ]),
    # ── COD ─────────────────────────────────────────────────────────────────
    _team("COD", "Congo DR", "cd", "#007FFF", [
        ("Lionel Mpasi",          "POR"), ("Aaron Wan-Bissaka",     "DEF"),
        ("Axel Tuanzebe",         "DEF"), ("Arthur Masuaku",        "DEF"),
        ("Chancel Mbemba",        "DEF"), ("Joris Kayembe",         "MED"),
        ("Charles Pickel",        "MED"), ("Ngal'ayel Mukau",       "MED"),
        ("Edo Kayembe",           "MED"), ("Samuel Moutoussamy",    "MED"),
        ("Noah Sadiki",           "MED"),
        ("Théo Bongonda",         "MED"), ("Meschak Elia",          "MED"),
        ("Yoane Wissa",           "DEL"), ("Brian Cipenga",         "DEL"),
        ("Fiston Mayele",         "DEL"), ("Cédric Bakambu",        "DEL"),
        ("Nathanaël Mbuku",       "DEL"),
    ]),
    # ── CRO ─────────────────────────────────────────────────────────────────
    _team("CRO", "Croacia", "hr", "#EF3340", [
        ("Dominik Livaković",     "POR"), ("Duje Caleta-Car",       "DEF"),
        ("Josko Gvardiol",        "DEF"), ("Josip Stanišić",        "DEF"),
        ("Luka Vušković",         "DEF"), ("Josip Sutalo",          "DEF"),
        ("Kristijan Jakic",       "MED"), ("Luka Modrić",           "MED"),
        ("Mateo Kovacic",         "MED"), ("Martin Baturina",       "MED"),
        ("Lovro Majer",           "MED"),
        ("Mario Pasalic",         "MED"), ("Petar Sucic",           "MED"),
        ("Ivan Perišić",          "DEL"), ("Marco Pasalic",         "MED"),
        ("Ante Budimir",          "DEL"), ("Andrej Kramarić",       "DEL"),
        ("Franjo Ivanovic",       "DEF"),
    ]),
    # ── CUW ─────────────────────────────────────────────────────────────────
    _team("CUW", "Curaçao", "cw", "#003C82", [
        ("Eloy Room",             "POR"), ("Armando Obispo",        "DEF"),
        ("Sherel Floranus",       "DEF"), ("Jurien Gaari",          "DEF"),
        ("Joshua Brenet",         "DEF"), ("Roshon Van Eijma",      "DEF"),
        ("Shurandy Sambo",        "MED"), ("Livano Comenencia",     "MED"),
        ("Godfried Roemeratoe",   "MED"), ("Juninho Bacuna",        "MED"),
        ("Leandro Bacuna",        "MED"),
        ("Tahith Chong",          "MED"), ("Kenji Gorre",           "MED"),
        ("Jearl Margaritha",      "DEL"), ("Jurgen Locadia",        "DEL"),
        ("Jeremy Antonisse",      "MED"), ("Gervane Kastaneer",     "DEL"),
        ("Sontje Hansen",         "DEL"),
    ]),
    # ── CZE ─────────────────────────────────────────────────────────────────
    _team("CZE", "Chequia", "cz", "#D7141A", [
        ("Matej Kovar",           "POR"), ("Jindrich Stanek",       "POR"),
        ("Ladislav Krejci",       "DEF"), ("Vladimir Coufal",       "DEF"),
        ("Jaroslav Zeleny",       "DEF"), ("Tomas Holes",           "DEF"),
        ("David Zima",            "DEF"), ("Michal Sadilek",        "MED"),
        ("Lukas Provod",          "MED"), ("Lukas Cerv",            "MED"),
        ("Tomas Soucek",          "MED"),
        ("Pavel Sulc",            "MED"), ("Matej Vydra",           "DEL"),
        ("Vasil Kusej",           "MED"), ("Tomas Chory",           "DEL"),
        ("Vaclav Cerny",          "DEL"), ("Adam Hlozek",           "DEL"),
        ("Patrik Schick",         "DEL"),
    ]),
    # ── ECU ─────────────────────────────────────────────────────────────────
    _team("ECU", "Ecuador", "ec", "#FFD100", [
        ("Hernán Galíndez",       "POR"), ("Gonzalo Valle",         "DEF"),
        ("Piero Hincapié",        "DEF"), ("Pervis Estupiñán",      "DEF"),
        ("Willian Pacho",         "DEF"), ("Ángelo Preciado",       "DEF"),
        ("Joel Ordóñez",          "DEF"), ("Moisés Caicedo",        "MED"),
        ("Alan Franco",           "MED"), ("Kendry Páez",           "MED"),
        ("Pedro Vite",            "MED"),
        ("John Yeboah",           "DEL"), ("Leonardo Campana",      "DEL"),
        ("Gonzalo Plata",         "DEL"), ("Nilson Angulo",         "DEL"),
        ("Alan Minda",            "DEL"), ("Kevin Rodríguez",       "MED"),
        ("Enner Valencia",        "DEL"),
    ]),
    # ── EGY ─────────────────────────────────────────────────────────────────
    _team("EGY", "Egipto", "eg", "#C8102E", [
        ("Mohamed El Shenawy",    "POR"), ("Mohamed Hany",          "DEF"),
        ("Mohamed Hamdy",         "DEF"), ("Yasser Ibrahim",        "DEF"),
        ("Khaled Sobhi",          "DEF"), ("Ramy Rabia",            "DEF"),
        ("Hossam Abdelmaguid",    "MED"), ("Ahmed Fatouh",          "MED"),
        ("Marwan Attia",          "MED"), ("Zizo",                  "MED"),
        ("Hamdy Fathy",           "MED"),
        ("Mohamed Lasheen",       "DEL"), ("Emam Ashour",           "MED"),
        ("Osama Faisal",          "DEL"), ("Mohamed Salah",         "DEL"),
        ("Mostafa Mohamed",       "DEL"), ("Trezeguet",             "DEL"),
        ("Omar Marmoush",         "DEL"),
    ]),
    # ── ENG ─────────────────────────────────────────────────────────────────
    _team("ENG", "England", "gb-eng", "#003090", [
        ("Jordan Pickford",       "POR"), ("John Stones",           "DEF"),
        ("Marc Guéhi",            "DEF"), ("Ezri Konsa",            "DEF"),
        ("Trent Alexander-Arnold","DEF"), ("Reece James",           "DEF"),
        ("Dan Burn",              "DEF"), ("Jordan Henderson",      "MED"),
        ("Declan Rice",           "MED"), ("Jude Bellingham",       "MED"),
        ("Cole Palmer",           "MED"),
        ("Morgan Rogers",         "MED"), ("Anthony Gordon",        "DEL"),
        ("Phil Foden",            "MED"), ("Bukayo Saka",           "DEL"),
        ("Harry Kane",            "DEL"), ("Marcus Rashford",       "DEL"),
        ("Ollie Watkins",         "DEL"),
    ]),
    # ── FRA ─────────────────────────────────────────────────────────────────
    _team("FRA", "Francia", "fr", "#003189", [
        ("Mike Maignan",          "POR"), ("Theo Hernandez",        "DEF"),
        ("William Saliba",        "DEF"), ("Jules Koundé",          "DEF"),
        ("Ibrahima Konaté",       "DEF"), ("Dayot Upamecano",       "DEF"),
        ("Lucas Digne",           "DEF"), ("Aurélien Tchouaméni",   "MED"),
        ("Eduardo Camavinga",     "MED"), ("Manu Koné",             "MED"),
        ("Adrien Rabiot",         "MED"),
        ("Michaël Olise",         "MED"), ("Ousmane Dembélé",       "DEL"),
        ("Bradley Barcola",       "DEL"), ("Désiré Doué",           "DEL"),
        ("Kingsley Coman",        "DEL"), ("Hugo Ekitike",          "DEL"),
        ("Kylian Mbappé",         "DEL"),
    ]),
    # ── GER ─────────────────────────────────────────────────────────────────
    _team("GER", "Alemania", "de", "#333333", [
        ("Marc-André ter Stegen", "POR"), ("Jonathan Tah",          "DEF"),
        ("David Raum",            "DEF"), ("Nico Schlotterbeck",    "DEF"),
        ("Antonio Rüdiger",       "DEF"), ("Waldemar Anton",        "DEF"),
        ("Ridle Baku",            "DEF"), ("Maximilian Mittelstadt","DEF"),
        ("Joshua Kimmich",        "MED"), ("Florian Wirtz",         "MED"),
        ("Felix Nmecha",          "MED"),
        ("Leon Goretzka",         "MED"), ("Jamal Musiala",         "MED"),
        ("Serge Gnabry",          "DEL"), ("Kai Havertz",           "DEL"),
        ("Leroy Sané",            "DEL"), ("Karim Adeyemi",         "DEL"),
        ("Nick Woltemade",        "DEL"),
    ]),
    # ── GHA ─────────────────────────────────────────────────────────────────
    _team("GHA", "Ghana", "gh", "#006B3F", [
        ("Lawrence Ati Zigi",     "POR"), ("Tariq Lamptey",         "DEF"),
        ("Mohammed Salisu",       "DEF"), ("Alidu Seidu",           "DEF"),
        ("Alexander Djiku",       "DEF"), ("Gideon Mensah",         "DEF"),
        ("Caleb Yirenkyi",        "DEF"), ("Abdul Issahaku Fatawu", "MED"),
        ("Thomas Partey",         "MED"), ("Salis Abdul Samed",     "MED"),
        ("Kamaldeen Sulemana",    "MED"),
        ("Mohammed Kudus",        "MED"), ("Iñaki Williams",        "DEL"),
        ("Jordan Ayew",           "DEL"), ("André Ayew",            "DEL"),
        ("Joseph Paintsil",       "DEL"), ("Osman Bukari",          "DEL"),
        ("Antoine Semenyo",       "DEL"),
    ]),
    # ── HAI ─────────────────────────────────────────────────────────────────
    _team("HAI", "Haití", "ht", "#00209F", [
        ("Johny Placide",         "POR"), ("Carlens Arcus",         "DEF"),
        ("Martin Expérience",     "DEF"), ("Jean-Kevin Duverne",    "DEF"),
        ("Ricardo Adé",           "DEF"), ("Duke Lacroix",          "DEF"),
        ("Garven Metusala",       "DEF"), ("Hannes Delcroix",       "DEF"),
        ("Leverton Pierre",       "MED"), ("Danley Jean Jacques",   "MED"),
        ("Jean-Ricner Bellegarde","MED"),
        ("Christopher Attys",     "MED"), ("Derrick Etienne Jr.",   "MED"),
        ("Josue Casimir",         "MED"), ("Ruben Providence",      "MED"),
        ("Duckens Nazon",         "DEL"), ("Louicius Deedson",      "DEL"),
        ("Frantzdy Pierrot",      "DEL"),
    ]),
    # ── IRN ─────────────────────────────────────────────────────────────────
    _team("IRN", "Irán", "ir", "#239F40", [
        ("Alireza Beiranvand",    "POR"), ("Morteza Pouraliganji",  "DEF"),
        ("Ehsan Hajsafi",         "DEF"), ("Milad Mohammadi",       "DEF"),
        ("Shojae Khalilzadeh",    "DEF"), ("Ramin Rezaeian",        "DEF"),
        ("Hossein Kanaani",       "MED"), ("Sadegh Moharrami",      "DEF"),
        ("Saleh Hardani",         "MED"), ("Saeed Ezatolahi",       "MED"),
        ("Saman Ghoddos",         "MED"),
        ("Omid Noorafkan",        "MED"), ("Roozbeh Cheshmi",       "DEF"),
        ("Mohammad Mohebi",       "MED"), ("Sardar Azmoun",         "DEL"),
        ("Mehdi Taremi",          "DEL"), ("Alireza Jahanbakhsh",   "DEL"),
        ("Ali Gholizadeh",        "DEL"),
    ]),
    # ── IRQ ─────────────────────────────────────────────────────────────────
    _team("IRQ", "Irak", "iq", "#007A3D", [
        ("Jalal Hassan",          "POR"), ("Rebin Sulaka",          "DEF"),
        ("Hussein Ali",           "DEF"), ("Akam Hashem",           "DEF"),
        ("Merchas Doski",         "DEF"), ("Zaid Tahseen",          "DEF"),
        ("Manaf Younis",          "MED"), ("Zidane Iqbal",          "MED"),
        ("Amir Al-Ammari",        "MED"), ("Ibrahim Bavesh",        "MED"),
        ("Ali Jasim",             "MED"),
        ("Youssef Amyn",          "MED"), ("Aimar Sher",            "MED"),
        ("Marko Farji",           "DEF"), ("Osama Rashid",          "MED"),
        ("Ali Al-Hamadi",         "DEL"), ("Aymen Hussein",         "DEL"),
        ("Mohanad Ali",           "DEL"),
    ]),
    # ── CIV ─────────────────────────────────────────────────────────────────
    _team("CIV", "Costa de Marfil", "ci", "#F77F00", [
        ("Yahia Fofana",          "POR"), ("Ghislain Konan",        "DEF"),
        ("Wilfried Singo",        "DEF"), ("Odilon Kossounou",      "DEF"),
        ("Evan Ndicka",           "DEF"), ("Willy Boly",            "DEF"),
        ("Emmanuel Agbadou",      "DEF"), ("Ousmane Diomandé",      "DEF"),
        ("Franck Kessié",         "MED"), ("Seko Fofana",           "MED"),
        ("Ibrahim Sangaré",       "MED"),
        ("Jean-Philippe Gbamin",  "MED"), ("Amad Diallo",           "DEL"),
        ("Sébastien Haller",      "DEL"), ("Simon Adingra",         "DEL"),
        ("Yan Diomandé",          "MED"), ("Evann Guessand",        "DEL"),
        ("Oumar Diakite",         "DEL"),
    ]),
    # ── JPN ─────────────────────────────────────────────────────────────────
    _team("JPN", "Japón", "jp", "#BC002D", [
        ("Zion Suzuki",           "POR"), ("Henry H. Mochizuki",    "DEF"),
        ("Ayumu Seko",            "DEF"), ("Junnosuke Suzuki",      "DEF"),
        ("Shogo Taniguchi",       "DEF"), ("Tsuyoshi Watanabe",     "DEF"),
        ("Kaishu Sano",           "DEF"), ("Yuki Soma",             "MED"),
        ("Ao Tanaka",             "MED"), ("Daichi Kamada",         "MED"),
        ("Takefusa Kubo",         "MED"),
        ("Ritsu Doan",            "MED"), ("Keito Nakamura",        "MED"),
        ("Takumi Minamino",       "MED"), ("Shuto Machino",         "DEL"),
        ("Junya Ito",             "DEL"), ("Koki Ogawa",            "DEL"),
        ("Ayase Ueda",            "DEL"),
    ]),
    # ── JOR ─────────────────────────────────────────────────────────────────
    _team("JOR", "Jordania", "jo", "#007A3D", [
        ("Yazeed Abulaila",       "POR"), ("Ihsan Haddad",          "DEF"),
        ("Mohammad Abu Hashish",  "DEF"), ("Yazan Al-Arab",         "DEF"),
        ("Abdallah Nasib",        "DEF"), ("Saleem Obaid",          "DEF"),
        ("Mohammad Abualnadi",    "MED"), ("Ibrahim Saadeh",        "MED"),
        ("Nizar Al-Rashdan",      "MED"), ("Noor Al-Rawabdeh",      "MED"),
        ("Mohannad Abu Taha",     "MED"),
        ("Amer Jamous",           "MED"), ("Musa Al-Taamari",       "DEL"),
        ("Yazan Al-Naimat",       "DEL"), ("Mahmoud Al-Mardi",      "MED"),
        ("Ali Olwan",             "DEF"), ("Mohammad Abu Zrayq",    "MED"),
        ("Ibrahim Sabra",         "DEL"),
    ]),
    # ── MEX ─────────────────────────────────────────────────────────────────
    _team("MEX", "México", "mx", "#006847", [
        ("Luis Malagón",          "POR"), ("Johan Vásquez",         "DEF"),
        ("Jorge Sánchez",         "DEF"), ("César Montes",          "DEF"),
        ("Jesús Gallardo",        "DEF"), ("Israel Reyes",          "DEF"),
        ("Diego Lainez",          "MED"), ("Carlos Rodríguez",      "MED"),
        ("Edson Álvarez",         "MED"), ("Orbelin Pineda",        "MED"),
        ("Marcel Ruiz",           "MED"),
        ("Érick Sánchez",         "MED"), ("Hirving Lozano",        "DEL"),
        ("Santiago Giménez",      "DEL"), ("Raúl Jiménez",          "DEL"),
        ("Alexis Vega",           "DEL"), ("Roberto Alvarado",      "MED"),
        ("César Huerta",          "DEL"),
    ]),
    # ── MAR ─────────────────────────────────────────────────────────────────
    _team("MAR", "Marruecos", "ma", "#C1272D", [
        ("Yassine Bounou",        "POR"), ("Munir El Kajoui",       "POR"),
        ("Achraf Hakimi",         "DEF"), ("Noussair Mazraoui",     "DEF"),
        ("Nayef Aguerd",          "DEF"), ("Romain Saïss",          "DEF"),
        ("Jawad El Yamiq",        "DEF"), ("Adam Masina",           "DEF"),
        ("Sofyan Amrabat",        "MED"), ("Azzedine Ounahi",       "MED"),
        ("Eliesse Ben Seghir",    "MED"),
        ("Bilal El Khannouss",    "MED"), ("Ismael Saibari",        "MED"),
        ("Youssef En-Nesyri",     "DEL"), ("Abde Ezzalzouli",       "DEL"),
        ("Soufiane Rahimi",       "DEL"), ("Brahim Díaz",           "MED"),
        ("Ayoub El Kaabi",        "DEL"),
    ]),
    # ── NED ─────────────────────────────────────────────────────────────────
    _team("NED", "Países Bajos", "nl", "#FF4F00", [
        ("Bart Verbruggen",       "POR"), ("Virgil van Dijk",       "DEF"),
        ("Micky van de Ven",      "DEF"), ("Jurriën Timber",        "DEF"),
        ("Denzel Dumfries",       "DEF"), ("Nathan Aké",            "DEF"),
        ("Jeremie Frimpong",      "DEF"), ("Jan Paul van Hecke",    "DEF"),
        ("Tijjani Reijnders",     "MED"), ("Ryan Gravenberch",      "MED"),
        ("Teun Koopmeiners",      "MED"),
        ("Frenkie de Jong",       "MED"), ("Xavi Simons",           "MED"),
        ("Justin Kluivert",       "DEL"), ("Memphis Depay",         "DEL"),
        ("Donyell Malen",         "DEL"), ("Wout Weghorst",         "DEL"),
        ("Cody Gakpo",            "DEL"),
    ]),
    # ── NZL ─────────────────────────────────────────────────────────────────
    _team("NZL", "Nueva Zelanda", "nz", "#000000", [
        ("Max Crocombe",          "POR"), ("Alex Paulsen",          "POR"),
        ("Michael Boxall",        "DEF"), ("Liberato Cacace",       "DEF"),
        ("Tim Payne",             "DEF"), ("Tyler Bindon",          "DEF"),
        ("Francis de Vries",      "DEF"), ("Finn Surman",           "MED"),
        ("Joe Bell",              "MED"), ("Sarpreet Singh",        "MED"),
        ("Ryan Thomas",           "MED"),
        ("Matthew Garbett",       "MED"), ("Marko Stamenić",        "MED"),
        ("Ben Old",               "MED"), ("Chris Wood",            "DEL"),
        ("Elijah Just",           "DEL"), ("Callum McCowatt",       "DEL"),
        ("Kosta Barbarouses",     "DEL"),
    ]),
    # ── NOR ─────────────────────────────────────────────────────────────────
    _team("NOR", "Noruega", "no", "#EF2B2D", [
        ("Ørjan Nyland",          "POR"), ("Julian Ryerson",        "DEF"),
        ("Leo Østigård",          "DEF"), ("Kristoffer Ajer",       "DEF"),
        ("Marcus H. Pedersen",    "DEF"), ("David Møller Wolfe",    "DEF"),
        ("Torbjørn Heggem",       "DEF"), ("Morten Thorsby",        "MED"),
        ("Martin Ødegaard",       "MED"), ("Sander Berge",          "MED"),
        ("Andreas Schjelderup",   "MED"),
        ("Patrick Berg",          "MED"), ("Erling Haaland",        "DEL"),
        ("Alexander Sørloth",     "DEL"), ("Aron Dønnum",           "MED"),
        ("Jørgen Strand Larsen",  "DEL"), ("Antonio Nusa",          "DEL"),
        ("Oscar Bobb",            "MED"),
    ]),
    # ── PAN ─────────────────────────────────────────────────────────────────
    _team("PAN", "Panamá", "pa", "#DA121A", [
        ("Orlando Mosquera",      "POR"), ("Luis Mejía",            "POR"),
        ("Fidel Escobar",         "DEF"), ("Andrés Andrade",        "DEF"),
        ("Michael Murillo",       "DEF"), ("Eric Davis",            "DEF"),
        ("José Córdoba",          "DEF"), ("César Blackman",        "MED"),
        ("Cristian Martínez",     "MED"), ("Aníbal Godoy",          "MED"),
        ("Adalberto Carrasquilla","MED"),
        ("Édgar Bárcenas",        "MED"), ("Carlos Harvey",         "DEF"),
        ("Ismael Díaz",           "DEL"), ("José Fajardo",          "DEL"),
        ("Cecilio Waterman",      "DEL"), ("José L. Rodríguez",     "MED"),
        ("Alberto Quintero",      "DEL"),
    ]),
    # ── PAR ─────────────────────────────────────────────────────────────────
    _team("PAR", "Paraguay", "py", "#D52B1E", [
        ("Roberto Fernandez",     "POR"), ("Orlando Gill",          "DEF"),
        ("Gustavo Gómez",         "DEF"), ("Fabián Balbuena",       "DEF"),
        ("Juan José Cáceres",     "DEF"), ("Omar Alderete",         "DEF"),
        ("Junior Alonso",         "DEF"), ("Mathías Villasanti",    "MED"),
        ("Diego Gómez",           "MED"), ("Damián Bobadilla",      "MED"),
        ("Andrés Cubas",          "MED"),
        ("Matias Galarza",        "MED"), ("Julio Enciso",          "DEL"),
        ("Kaku Romero",           "MED"), ("Miguel Almirón",        "MED"),
        ("Ramón Sosa",            "DEL"), ("Ángel Romero",          "DEL"),
        ("Antonio Sanabria",      "DEL"),
    ]),
    # ── POR ─────────────────────────────────────────────────────────────────
    _team("POR", "Portugal", "pt", "#006600", [
        ("Diogo Costa",           "POR"), ("José Sá",               "POR"),
        ("Rúben Dias",            "DEF"), ("João Cancelo",          "DEF"),
        ("Diogo Dalot",           "DEF"), ("Nuno Mendes",           "DEF"),
        ("Gonçalo Inácio",        "DEF"), ("Bernardo Silva",        "MED"),
        ("Bruno Fernandes",       "MED"), ("Rúben Neves",           "MED"),
        ("Vitinha",               "MED"),
        ("João Neves",            "MED"), ("Cristiano Ronaldo",     "DEL"),
        ("Francisco Trincão",     "DEL"), ("João Félix",            "DEL"),
        ("Gonçalo Ramos",         "DEL"), ("Pedro Neto",            "DEL"),
        ("Rafael Leão",           "DEL"),
    ]),
    # ── QAT ─────────────────────────────────────────────────────────────────
    _team("QAT", "Catar", "qa", "#8D1B3D", [
        ("Meshaal Barsham",       "POR"), ("Sultan Albrake",        "DEF"),
        ("Lucas Mendes",          "DEF"), ("Homam Ahmed",           "DEF"),
        ("Boualem Khoukhi",       "DEF"), ("Pedro Miguel",          "DEF"),
        ("Tarek Salman",          "MED"), ("Mohamed Al-Mannai",     "MED"),
        ("Karim Boudiaf",         "MED"), ("Assim Madibo",          "MED"),
        ("Ahmed Fatehi",          "MED"),
        ("Mohammed Waad",         "DEF"), ("Abdulaziz Hatem",       "MED"),
        ("Hassan Al-Haydos",      "MED"), ("Edmilson Junior",       "MED"),
        ("Akram Afif",            "DEL"), ("Ahmed Al Ganehi",       "MED"),
        ("Almoez Ali",            "DEL"),
    ]),
    # ── KSA ─────────────────────────────────────────────────────────────────
    _team("KSA", "Arabia Saudita", "sa", "#006C35", [
        ("Nawaf Alaqidi",         "POR"), ("Abdulrahman Al-Sanbi",  "DEF"),
        ("Saud Abdulhamid",       "DEF"), ("Nawaf Bouwashl",        "DEF"),
        ("Jihad Thakri",          "DEF"), ("Moteb Al-Harbi",        "DEF"),
        ("Hassan Altambakti",     "DEF"), ("Musab Aljuwayr",        "MED"),
        ("Ziyad Aljohani",        "MED"), ("Abdullah Alkhaibari",   "MED"),
        ("Nasser Aldawsari",      "MED"),
        ("Saleh Abu Alshamat",    "MED"), ("Marwan Alsahafi",       "DEF"),
        ("Salem Aldawsari",       "DEL"), ("Abdulrahman Al-Aboud",  "MED"),
        ("Feras Alkbrikan",       "DEL"), ("Saleh Alshehri",        "DEL"),
        ("Abdullah Al-Hamdan",    "DEL"),
    ]),
    # ── SCO ─────────────────────────────────────────────────────────────────
    _team("SCO", "Escocia", "gb-sct", "#003F87", [
        ("Angus Gunn",            "POR"), ("Jack Hendry",           "DEF"),
        ("Kieran Tierney",        "DEF"), ("Aaron Hickey",          "DEF"),
        ("Andrew Robertson",      "DEF"), ("Scott McKenna",         "DEF"),
        ("John Souttar",          "DEF"), ("Anthony Ralston",       "DEF"),
        ("Grant Hanley",          "DEF"), ("Scott McTominay",       "MED"),
        ("Billy Gilmour",         "MED"),
        ("Lewis Ferguson",        "MED"), ("Ryan Christie",         "MED"),
        ("Kenny McLean",          "MED"), ("John McGinn",           "MED"),
        ("Lyndon Dykes",          "DEL"), ("Che Adams",             "DEL"),
        ("Ben Doak",              "MED"),
    ]),
    # ── SEN ─────────────────────────────────────────────────────────────────
    _team("SEN", "Senegal", "sn", "#00853F", [
        ("Édouard Mendy",         "POR"), ("Yehvann Diouf",         "POR"),
        ("Moussa Niakhaté",       "DEF"), ("Abdoulaye Seck",        "DEF"),
        ("Ismail Jakobs",         "DEF"), ("El Hadji M. Diouf",     "DEF"),
        ("Kalidou Koulibaly",     "DEF"), ("Idrissa Gana Gueye",    "MED"),
        ("Pape Matar Sarr",       "MED"), ("Pape Gueye",            "MED"),
        ("Habib Diarra",          "MED"),
        ("Lamine Camara",         "MED"), ("Sadio Mané",            "DEL"),
        ("Ismaïla Sarr",          "DEL"), ("Boulaye Dia",           "DEL"),
        ("Iliman Ndiaye",         "DEL"), ("Nicolas Jackson",       "DEL"),
        ("Krepin Diatta",         "MED"),
    ]),
    # ── RSA ─────────────────────────────────────────────────────────────────
    _team("RSA", "Sudáfrica", "za", "#007A4D", [
        ("Ronwen Williams",       "POR"), ("Sipho Chaine",          "POR"),
        ("Aubrey Modiba",         "DEF"), ("Samukele Kabini",       "DEF"),
        ("Mbekezeli Mbokazi",     "DEF"), ("Khulumani Ndamane",     "DEF"),
        ("Siyabonga Ngezana",     "DEF"), ("Khuliso Mudau",         "DEF"),
        ("Nkosinathi Sibisi",     "DEF"), ("Teboho Mokoena",        "MED"),
        ("Thalente Mbatha",       "MED"),
        ("Bathasi Aubaas",        "MED"), ("Yaya Sithole",          "MED"),
        ("Sipho Mbule",           "MED"), ("Lyle Foster",           "DEL"),
        ("Iqraam Rayners",        "DEL"), ("Mohau Nkota",           "DEL"),
        ("Oswin Appollis",        "DEL"),
    ]),
    # ── KOR ─────────────────────────────────────────────────────────────────
    _team("KOR", "Corea del Sur", "kr", "#C8102E", [
        ("Hyeon-woo Jo",          "POR"), ("Seung-Gyu Kim",         "POR"),
        ("Min-jae Kim",           "DEF"), ("Yu-min Cho",            "DEF"),
        ("Young-woo Seol",        "DEF"), ("Han-beom Lee",          "DEF"),
        ("Tae-seok Lee",          "DEF"), ("Myung-jae Lee",         "DEF"),
        ("Jae-sung Lee",          "MED"), ("In-beom Hwang",         "MED"),
        ("Kang-in Lee",           "MED"),
        ("Seung-ho Paik",         "MED"), ("Jens Castrop",          "MED"),
        ("Dong-yeong Lee",        "MED"), ("Gue-sung Cho",          "DEL"),
        ("Heung-min Son",         "DEL"), ("Hee-chan Hwang",         "DEL"),
        ("Hyeon-Gyu Oh",          "DEL"),
    ]),
    # ── ESP ─────────────────────────────────────────────────────────────────
    _team("ESP", "España", "es", "#AA151B", [
        ("Unai Simón",            "POR"), ("Robin Le Normand",      "DEF"),
        ("Aymeric Laporte",       "DEF"), ("Dean Huijsen",          "DEF"),
        ("Pedro Porro",           "DEF"), ("Dani Carvajal",         "DEF"),
        ("Marc Cucurella",        "DEF"), ("Martín Zubimendi",      "MED"),
        ("Rodri",                 "MED"), ("Pedri",                 "MED"),
        ("Fabián Ruiz",           "MED"),
        ("Mikel Merino",          "MED"), ("Lamine Yamal",          "DEL"),
        ("Dani Olmo",             "MED"), ("Nico Williams",         "DEL"),
        ("Ferran Torres",         "DEL"), ("Álvaro Morata",         "DEL"),
        ("Mikel Oyarzabal",       "DEL"),
    ]),
    # ── SWE ─────────────────────────────────────────────────────────────────
    _team("SWE", "Suecia", "se", "#006AA7", [
        ("Victor Johansson",      "POR"), ("Isak Hien",             "DEF"),
        ("Gabriel Gudmundsson",   "DEF"), ("Emil Holm",             "DEF"),
        ("Victor N. Lindelöf",    "DEF"), ("Gustaf Lagerbielke",    "DEF"),
        ("Lucas Bergvall",        "MED"), ("Hugo Larsson",          "MED"),
        ("Jesper Karlström",      "MED"), ("Yasin Ayari",           "MED"),
        ("Mattias Svanberg",      "MED"),
        ("Daniel Svensson",       "MED"), ("Ken Sema",              "MED"),
        ("Roony Bardghji",        "DEL"), ("Dejan Kulusevski",      "DEL"),
        ("Anthony Elanga",        "DEL"), ("Alexander Isak",        "DEL"),
        ("Viktor Gyökeres",       "DEL"),
    ]),
    # ── SUI ─────────────────────────────────────────────────────────────────
    _team("SUI", "Suiza", "ch", "#FF0000", [
        ("Gregor Kobel",          "POR"), ("Yvon Mvogo",            "POR"),
        ("Manuel Akanji",         "DEF"), ("Ricardo Rodríguez",     "DEF"),
        ("Nico Elvedi",           "DEF"), ("Aurèle Amenda",         "DEF"),
        ("Silvan Widmer",         "DEF"), ("Granit Xhaka",          "MED"),
        ("Denis Zakaria",         "MED"), ("Remo Freuler",          "MED"),
        ("Fabian Rieder",         "MED"),
        ("Ardon Jashari",         "MED"), ("Johan Manzambi",        "MED"),
        ("Michel Aebischer",      "MED"), ("Breel Embolo",          "DEL"),
        ("Rubén Vargas",          "DEL"), ("Dan Ndoye",             "DEL"),
        ("Zeki Amdouni",          "DEL"),
    ]),
    # ── TUN ─────────────────────────────────────────────────────────────────
    _team("TUN", "Túnez", "tn", "#E70013", [
        ("Bechir Ben Said",       "POR"), ("Aymen Dahmen",          "POR"),
        ("Yan Valery",            "DEF"), ("Montassar Talbi",       "DEF"),
        ("Yassine Meriah",        "DEF"), ("Ali Abdi",              "DEF"),
        ("Dylan Bronn",           "DEF"), ("Ellyes Skhiri",         "MED"),
        ("Aissa Laidouni",        "MED"), ("Ferjani Sassi",         "MED"),
        ("M.A. Ben Romdhane",     "MED"),
        ("Hannibal Mejbri",       "MED"), ("Elias Achouri",         "MED"),
        ("Elias Saad",            "MED"), ("Hazem Mastouri",        "DEL"),
        ("Ismael Gharbi",         "MED"), ("Sayfallah Ltaief",      "DEL"),
        ("Naim Sliti",            "DEL"),
    ]),
    # ── TUR ─────────────────────────────────────────────────────────────────
    _team("TUR", "Türkiye", "tr", "#E30A17", [
        ("Ugurcan Cakir",         "POR"), ("Mert Muldur",           "DEF"),
        ("Zeki Celik",            "DEF"), ("Abdulkerim Bardakci",   "DEF"),
        ("Caglar Soyuncu",        "DEF"), ("Merih Demiral",         "DEF"),
        ("Ferdi Kadioglu",        "DEF"), ("Kaan Ayhan",            "MED"),
        ("Ismail Yuksek",         "MED"), ("Hakan Calhanoglu",      "MED"),
        ("Orkun Kokcu",           "MED"),
        ("Arda Güler",            "MED"), ("Irfan Can Kahveci",     "MED"),
        ("Yunus Akgün",           "MED"), ("Can Uzun",              "DEL"),
        ("Baris Alper Yilmaz",    "DEL"), ("Kerem Aktürkoglu",      "DEL"),
        ("Kenan Yildiz",          "DEL"),
    ]),
    # ── URU ─────────────────────────────────────────────────────────────────
    _team("URU", "Uruguay", "uy", "#5EB6E4", [
        ("Sergio Rochet",         "POR"), ("Santiago Mele",         "POR"),
        ("Ronald Araújo",         "DEF"), ("José M. Giménez",       "DEF"),
        ("Sebastián Cáceres",     "DEF"), ("Mathias Olivera",       "DEF"),
        ("Guillermo Varela",      "DEF"), ("Nahitán Nández",        "MED"),
        ("Federico Valverde",     "MED"), ("G. De Arrascaeta",      "MED"),
        ("Rodrigo Bentancur",     "MED"),
        ("Manuel Ugarte",         "MED"), ("Nicolás de la Cruz",    "MED"),
        ("Maxi Araújo",           "DEL"), ("Darwin Núñez",          "DEL"),
        ("Federico Viñas",        "DEL"), ("Rodrigo Aguirre",       "DEL"),
        ("Facundo Pellistri",     "DEL"),
    ]),
    # ── USA ─────────────────────────────────────────────────────────────────
    _team("USA", "Estados Unidos", "us", "#002868", [
        ("Matt Freese",           "POR"), ("Chris Richards",        "DEF"),
        ("Tim Ream",              "DEF"), ("Mark McKenzie",         "DEF"),
        ("Alex Freeman",          "DEF"), ("Antonee Robinson",      "DEF"),
        ("Tyler Adams",           "MED"), ("Tanner Tessmann",       "MED"),
        ("Weston McKennie",       "MED"), ("Christian Roldan",      "MED"),
        ("Timothy Weah",          "MED"),
        ("Diego Luna",            "MED"), ("Malik Tillman",         "MED"),
        ("Christian Pulisic",     "DEL"), ("Brenden Aaronson",      "MED"),
        ("Ricardo Pepi",          "DEL"), ("Haji Wright",           "DEL"),
        ("Folarin Balogun",       "DEL"),
    ]),
    # ── UZB ─────────────────────────────────────────────────────────────────
    _team("UZB", "Uzbekistán", "uz", "#1EB53A", [
        ("Utkir Yusupov",         "POR"), ("Farrukh Savfiev",       "DEF"),
        ("Sherzod Nasrullaev",    "DEF"), ("Umar Eshmurodov",       "DEF"),
        ("Husniddin Aliqulov",    "DEF"), ("Rustamjon Ashurmatov",  "DEF"),
        ("Khojiakbar Alijonov",   "MED"), ("Abdukodir Khusanov",    "MED"),
        ("Odiljon Hamrobekov",    "MED"), ("Otabek Shukurov",       "MED"),
        ("Jamshid Iskanderov",    "MED"),
        ("Azizbek Turgunboev",    "MED"), ("Khojimat Erkinov",      "MED"),
        ("Eldor Shomurodov",      "DEL"), ("Oston Urunov",          "MED"),
        ("Jaloliddin Masharipov", "MED"), ("Igor Sergeev",          "DEF"),
        ("Abbosbek Fayzullaev",   "MED"),
    ]),
    # ── ALG ─────────────────────────────────────────────────────────────────
    _team("ALG", "Algeria", "dz", "#006233", [
        ("Alexis Guendouz",       "POR"), ("Ramy Bensebaini",       "DEF"),
        ("Youcef Atal",           "DEF"), ("Rayan Aït-Nouri",       "DEF"),
        ("Mohamed Amine Tougai",  "DEF"), ("Aïssa Mandi",           "DEF"),
        ("Ismael Bennacer",       "MED"), ("Houssem Aquar",         "MED"),
        ("Hicham Boudaoui",       "MED"), ("Ramiz Zerrouki",        "MED"),
        ("Nabil Bentalab",        "MED"),
        ("Farés Chaibi",          "MED"), ("Riyad Mahrez",          "DEL"),
        ("Said Benrahma",         "DEL"), ("Anis Hadj Moussa",      "DEL"),
        ("Amine Gouiri",          "DEL"), ("Baghdad Bounedjah",     "DEL"),
        ("Mohammed Amoura",       "DEL"),
    ]),
]

# ── Fichas especiales FWC ────────────────────────────────────────────────────
SPECIAL_STICKERS = [
    {"id": "00",    "team": "FWC", "name": "Logo Panini",            "pos": "ESP", "foil": True,  "photo": False},
    {"id": "FWC1",  "team": "FWC", "name": "Emblema Oficial",        "pos": "ESP", "foil": True,  "photo": False},
    {"id": "FWC2",  "team": "FWC", "name": "Emblema Oficial 2",      "pos": "ESP", "foil": True,  "photo": False},
    {"id": "FWC3",  "team": "FWC", "name": "Mascota Oficial",        "pos": "ESP", "foil": True,  "photo": False},
    {"id": "FWC4",  "team": "FWC", "name": "Slogan Oficial",         "pos": "ESP", "foil": True,  "photo": False},
    {"id": "FWC5",  "team": "FWC", "name": "Balón Oficial",          "pos": "ESP", "foil": False, "photo": False},
    {"id": "FWC6",  "team": "FWC", "name": "Sede: USA",              "pos": "ESP", "foil": True,  "photo": False},
    {"id": "FWC7",  "team": "FWC", "name": "Sede: Canadá",           "pos": "ESP", "foil": True,  "photo": False},
    {"id": "FWC8",  "team": "FWC", "name": "Sede: México",           "pos": "ESP", "foil": True,  "photo": False},
    {"id": "FWC9",  "team": "FWC", "name": "Historia: Italia 1934",  "pos": "ESP", "foil": False, "photo": False},
    {"id": "FWC10", "team": "FWC", "name": "Historia: Uruguay 1950", "pos": "ESP", "foil": False, "photo": False},
    {"id": "FWC11", "team": "FWC", "name": "Historia: Alemania 1954","pos": "ESP", "foil": False, "photo": False},
    {"id": "FWC12", "team": "FWC", "name": "Historia: Brasil 1962",  "pos": "ESP", "foil": False, "photo": False},
    {"id": "FWC13", "team": "FWC", "name": "Historia: Alemania 1974","pos": "ESP", "foil": False, "photo": False},
    {"id": "FWC14", "team": "FWC", "name": "Historia: Argentina 1986","pos":"ESP", "foil": False, "photo": False},
    {"id": "FWC15", "team": "FWC", "name": "Historia: Brasil 1994",  "pos": "ESP", "foil": False, "photo": False},
    {"id": "FWC16", "team": "FWC", "name": "Historia: Brasil 2002",  "pos": "ESP", "foil": False, "photo": False},
    {"id": "FWC17", "team": "FWC", "name": "Historia: Italia 2006",  "pos": "ESP", "foil": False, "photo": False},
    {"id": "FWC18", "team": "FWC", "name": "Historia: Alemania 2014","pos": "ESP", "foil": False, "photo": False},
    {"id": "FWC19", "team": "FWC", "name": "Historia: Argentina 2022","pos":"ESP", "foil": False, "photo": False},
]

# ── Indices ───────────────────────────────────────────────────────────────────
TEAM_STICKERS: list = []
for t in TEAMS:
    TEAM_STICKERS.extend(t["stickers"])

ALL_STICKERS: list = SPECIAL_STICKERS + TEAM_STICKERS
TEAM_BY_CODE: dict = {t["code"]: t for t in TEAMS}
